Models/DiningMenu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiningMenu
    {
        public int id { get; set; }
        public Nullable<int> serial { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string image { get; set; }
    }
}

Models/DiningRegistration.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiningRegistration
    {
        public int id { get; set; }
        public string name { get; set; }
        public string desig { get; set; }
        public string home { get; set; }
        public string contact { get; set; }
        public string hall { get; set; }
        public string email { get; set; }
        public string pwd { get; set; }
        public string image { get; set; }
    }
}

Controllers/DiningAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using HallManagementSystem.Models;
namespace HallManagementSystem.Controllers
{
    public class DiningAdminController : Controller
    {
        //
        // GET: /DiningAdmin/
        sb2 db = new sb2();

        public ActionResult Dining()
        {
            return View();
        }
        public ActionResult DiningRegistration()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DiningRegistration(string name, string desig, string home, string contact, string hall, string email, string pwd, HttpPostedFileBase file)
        {

            var path = "";
            var photoPath = "";

            if (file != null)
            {
                if (file.ContentLength > 0)
                {
                    if (Path.GetExtension(file.FileName).ToLower() == ".jpg"
                        || Path.GetExtension(file.FileName).ToLower() == ".png"
                              || Path.GetExtension(file.FileName).ToLower() == ".gif"
                                    || Path.GetExtension(file.FileName).ToLower() == ".jpeg")
                    {
                        path = Path.Combine(Server.MapPath("~/Content"), file.FileName);
                        file.SaveAs(path);
                        //photoPath = "~/Images/" + file.FileName; 
                        photoPath = file.FileName;
                    }
                }
            }

            DiningRegistration dngregg = new DiningRegistration();
            dngregg.name = name;
            dngregg.desig = desig;
            dngregg.home = home;
            dngregg.contact = contact;
            dngregg.hall = hall;
            dngregg.email = email;
            dngregg.pwd = pwd;
            dngregg.image = photoPath;


            db.DiningRegistrations.Add(dngregg);
            db.SaveChanges();

            return RedirectToAction("Login", "Provost");

            //   return View();
        }

        public ActionResult DiningMenu()
        {
            return View();
        }
        public ActionResult DiningLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DiningMenu(int serial,string name,string price,  HttpPostedFileBase file)
        {

            var path = "";
            var photoPath = "";

            if (file != null)
            {
                if (file.ContentLength > 0)
                {
                    if (Path.GetExtension(file.FileName).ToLower() == ".jpg"
                        || Path.GetExtension(file.FileName).ToLower() == ".png"
                              || Path.GetExtension(file.FileName).ToLower() == ".gif"
                                    || Path.GetExtension(file.FileName).ToLower() == ".jpeg")
                    {
                        path = Path.Combine(Server.MapPath("~/Content"), file.FileName);
                        file.SaveAs(path);
                        //photoPath = "~/Images/" + file.FileName; 
                        photoPath = file.FileName;
                    }
                }
            }

          

            DiningMenu menu = new DiningMenu();
            menu.serial = serial;
            menu.name = name;
            menu.price = price;
            menu.image = photoPath;

            db.DiningMenus.Add(menu);
            db.SaveChanges();

            return RedirectToAction("Login", "Provost");

            //   return View();
        }
        public ActionResult DiningMenuView(int id)
        {
            var menuview = from s in db.DiningMenus select s;
            if (menuview !=null)
            {
                menuview = menuview.Where(c => c.id == id);
            }
            return View(menuview);
        }
	}
}

Views/DiningAdmin/Dining.cshtml
@{
    ViewBag.Title = "Dining";
    Layout = "~/Views/Shared/_DiningAdmin.cshtml";
}

<div class="col-md-4">

</div>
<div class="col-md-4">
    <h2>Login</h2>
    @using (Html.BeginForm("Registration", "Main", FormMethod.Post, new { enctype = "multipart/form-data", name = "reg", id = "reg" }))
    {
        <form role="form">
            <div class="form-group">
                <label for="email">Email address:</label>
                <input type="email" class="form-control" id="email">
            </div>
            <div class="form-group">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" id="pwd">
            </div>
            <div class="checkbox">
                <label><input type="checkbox"> Remember me</label>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    }
</div>
<div class="col-md-4">

</div>

Views/DiningAdmin/DiningLogin.cshtml
@{
    ViewBag.Title = "DiningLogin";
    Layout = "~/Views/Shared/_DiningLogin.cshtml";
}

<div class="col-md-4">

</div>
<div class="col-md-4">
    <h2>Login</h2>
    @using (Html.BeginForm("Login", "Provost", FormMethod.Post, new { enctype = "multipart/form-data", name = "reg", id = "reg" }))
    {
        <form role="form">
            <div class="form-group">
                <label for="email">Email Address:</label>
                <input type="email" class="form-control" name="email" id="email">
            </div>
            <div class="form-group">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" name="pwd" id="pwd">
            </div>
            <div class="checkbox">
                <label><input type="checkbox"> Remember me</label>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    }
</div>
<div class="col-md-4">

</div>

Views/DiningAdmin/DiningMenu.cshtml
@{
    ViewBag.Title = "DiningMenu";
    Layout = "~/Views/Shared/_DiningMenu.cshtml";
}
<h2>Today's Menu</h2>
@using (Html.BeginForm("DiningMenu", "DiningAdmin", FormMethod.Post, new { enctype = "multipart/form-data", name = "reg", id = "reg" }))
    {
    <form role="form">
        <div class="row">

            <div class="col-md-2">

                <div class="form-group">
                    <label for="serial">Serial No:</label>
                    <input type="text" class="form-control" name="serial" id="serial">
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="name" id="name">

                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <label for="price">Price :</label>
                    <input type="text" class="form-control" name="price" id="price">

                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label for="image">Image  :</label>
                    <input type="file" class="form-control" name="file" id="file">
                </div>
            </div>

        </div>



        <div class="row">
            <div class="col-md-10">

            </div>

            <div class="col-md-2">
                <button type="submit" class="btn btn-default">Post</button>

                
            </div>
        </div>
    </form>
}

Views/DiningAdmin/DiningMenuView.cshtml
@using HallManagementSystem.Models;
@model IEnumerable<DiningMenu>
@{
    ViewBag.Title = "DiningMenuView";
    Layout = "~/Views/Shared/_DiningMenu.cshtml";
}

<h3>Today's Menu</h3>
<div class="col-md-2">
    @{
        foreach (var item in Model)
        {
            <p>Serial: @item.serial</p>      
        }
    }
</div>
<div class="col-md-4">
    @{
        foreach (var item in Model)
        {
            
            <p>Name: @item.name</p>
        }
    }
</div>
<div class="col-md-2">
    @{
        foreach (var item in Model)
        {
            <p>Price: @item.price</p>
        }
    }
</div>
<div class="col-md-4">
    @{
        foreach (var item in Model)
        {
           <p> <img src="~/Content/@item.image" class="img-thumbnail" alt="Cinque Terre" width="150" height="110"></p>          
        }
    }
</div>

Views/DiningAdmin/DiningRegistration.cshtml
@{
    ViewBag.Title = "DiningRegistration";
    Layout = "~/Views/Shared/_DiningRegistration.cshtml";
}

<div class="col-md-4">

</div>
<div class="col-md-4">
    <h2>Dining Registration</h2>
    @using (Html.BeginForm("DiningRegistration", "DiningAdmin", FormMethod.Post, new { enctype = "multipart/form-data", name = "reg", id = "reg" }))
    {
        <form role="form">
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" id="name">
            </div>
            <div class="form-group">
                <label for="desig">Designation:</label>
                <select id="desig" class="form-control" name="desig">


                    <option value="Guide">Guide</option>

                    <option value="Waiter">Waiter</option>

                    <option selected="Manager" value="Guide">Manager</option>
                </select>
            </div>           
            <div class="form-group">
                <label for="home">Home Town :</label>
                <input type="text" class="form-control" name="home" id="home">
            </div>
            <div class="form-group">
                <label for="contact">Contact Number :</label>
                <input type="text" class="form-control" name="contact" id="contact">
            </div>

            <div class="form-group">
                <label for="hall">Hall Name:</label>
                <select id="hall" class="form-control" name="hall">

                    <option value=""></option>

                    <option value="0">D1</option>

                    <option value="1">D3</option>

                    <option selected="selected" value="2">Sher E Bangla Hall-2</option>

                    <option value="3">D4</option>

                </select>
            </div>
            <div class="form-group">
                <label for="email">Email address:</label>
                <input type="email" class="form-control" name="email" id="email">
            </div>
            <div class="form-group">
                <label for="pwd">Password:</label>
                <input type="password" class="form-control" name="pwd" id="pwd">
            </div>
            <div class="form-group">
                <label for="image">Image:</label>
                <input type="file" class="form-control" name="file" id="file">
            </div>
            <div class="checkbox">
                <label><input type="checkbox"> Remember me</label>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    }
</div>
<div class="col-md-4">

</div>